### ISSUE TITLE
Add README + LICENCE

### ISSUE THREAD

**Issue by maelle** [r-hub/branding#1]
What should the license be?

Besides, can anyone use the logo when presenting/mentioning R-hub in a presentation/talk? I'd like to write that in the README (occasion to tell folks that if they do present R-hub somewhere, they should tell us via gitter/GitHub).

**Comment by gaborcsardi** [comment]
IDK if we need a license for the artwork. We don't really anticipate derivative works here, are we? And common law trademark rights should be enough for us.

**Comment by maelle** [comment]
Ok! Do you agree that anyone presenting/mentioning R-hub can use the logos?

**Comment by gaborcsardi** [comment]
Sure. That's fair use, anyway, I don't need to agree. Even if it was a
trademark, that would be fine.
